- name: Find all files in the current args dir
  ansible.builtin.find:
    paths: "/var/snap/microk8s/current/args/"
    recurse: true
  register: args
  
- name: Read current secure port
  ansible.builtin.set_fact:
    current_secure_port: 16443 #"{{ lookup('file', '/var/snap/microk8s/current/args/kube-apiserver') | regex_search('^--secure-port=([0-9]+)') }}"
  register: current_secure_port_result
  ignore_errors: true
  
- name: Change API server secure port to {{ microk8s_config_api_server_secure_port }}
  become: true
  ansible.builtin.replace:
    path: /var/snap/microk8s/current/args/kube-apiserver
    regexp: '--secure-port=\d+'
    replace: '--secure-port={{ microk8s_config_api_server_secure_port }}'
  when: microk8s_config_api_server_secure_port is defined

- name: Replace current secure port to {{ microk8s_config_api_server_secure_port }} in all files
  become: true
  replace:
    path: "{{ item.path }}"
    regexp: '{{ current_secure_port_result }}'
    replace: '{{ microk8s_config_api_server_secure_port }}'
  with_items: "{{ args.files }}"

- name: Create ~/.kube dir if not exists
  ansible.builtin.file:
    path: ~/.kube
    state: directory
    mode: '0750'

- name: Create config if not exists
  become: true
  command: /snap/bin/microk8s.config -l > ~/.kube/config 

- name: Replace current server port in kube config file
  replace:
    path: "~/.kube/config"
    regexp: '{{ current_secure_port_result }}'
    replace: '{{ microk8s_config_api_server_secure_port }}'

- name: Create overrides dir
  become: true
  ansible.builtin.file:
    path: /var/snap/microk8s/current/config_overrides
    state: directory
    mode: '0777'

- name: Copy content from credentials dir to config_ovrrides
  become: true
  ansible.builtin.copy:
    src: /var/snap/microk8s/current/credentials/
    dest: /var/snap/microk8s/current/config_overrides/


- name: Find all files in the current config_overrides dir
  ansible.builtin.find:
    paths: "/var/snap/microk8s/current/config_overrides/"
    recurse: true
  register: config_overrides

- name: Replace current secure port to {{ microk8s_config_api_server_secure_port }} in all files
  become: true
  replace:
    path: "{{ item.path }}"
    regexp: '{{ current_secure_port_result }}'
    replace: '{{ microk8s_config_api_server_secure_port }}'
  with_items: "{{ config_overrides.files }}"

- name: Replace current server port in all config files
  become: true
  replace:
    path: "/var/snap/microk8s/current/config_overrides/client.config"
    regexp: '{{ current_secure_port_result }}'
    replace: '{{ microk8s_config_api_server_secure_port }}'
  
- name: Replace path to configs for all files
  become: true
  replace:
    path: "{{ item.path }}"
    regexp: '$SNAP_DATA/credentials/'
    replace: '$SNAP_DATA/config_overrides/'
  with_items: "{{ args.files }}"


- name: Disable microk8s
  become: true
  snap:
    name: microk8s
    classic: yes
    channel: "{{ microk8s_version }}"
    state: disabled

- name: Enable microk8s
  become: true
  snap:
    name: microk8s
    classic: yes
    channel: "{{ microk8s_version }}"
    state: enabled